sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker
before_install: 
    - docker build -t kevinli92924/sample-docker-test -f Dockerfile.dev .
script:     
    - docker run -e CI=true kevinli92924/sample-docker-test npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2" ### AWS region of your choice
  app: "sample-docker-react" ### Your EB App name
  env: "Sampledockerreact-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-ap-southeast-2-865762978809" ### S3 bucket name
  bucket_path: "EBApptest" ### S3 folder name under S3 bucket above
  on:
    branch: main
  access_key_id: "AKIA4TE36VP46P6LG4VM"
  secret_access_key: "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"